language: node_js
node_js:
  - "5.4.0"
  - "4.2.1"
  - "iojs-v3.3.1"
  - "iojs-v2.5.0"
script:
  - npm run cover
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
